name: Build and Push Docker Images

on:
    push:
        branches:
            - main
    workflow_dispatch: # Allows manual triggering

jobs:
    build-and-push:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21' # Adjust to your Java version

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Build and Push Service Image
              run: |
                echo "Building and pushing event-models"
                mvn clean compile
                mvn jib:build -Ddocker.username=${{ secrets.DOCKER_USERNAME }}

    notify:
        name: Notify via Email
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Send Email Notification
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: ${{ secrets.SMTP_HOST }}
                  server_port: ${{ secrets.SMTP_PORT }}
                  username: ${{ secrets.SMTP_USERNAME }}
                  password: ${{ secrets.SMTP_PASSWORD }}
                  subject: Build and Push Workflow Status
                  body: |
                      The Build and Push workflow has completed.
                      Check the results here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  to: ${{ secrets.EMAIL }}
                  from: GitHub Actions <${{ secrets.SMTP_USERNAME }}>
